const config = {
  presets: ['@babel/preset-env', '@babel/preset-react'],
  plugins: [
    'react-hot-loader/babel',
    'dynamic-import-node',
    'styled-components',
    '@babel/plugin-proposal-class-properties',
    // '@babel/plugin-proposal-decorators',
    // '@babel/plugin-proposal-do-expressions',
    // '@babel/plugin-proposal-export-default-from',
    // '@babel/plugin-proposal-export-namespace-from',
    // '@babel/plugin-proposal-function-sent',
    // '@babel/plugin-proposal-json-strings',
    // '@babel/plugin-proposal-logical-assignment-operators',
    // '@babel/plugin-proposal-nullish-coalescing-operator',
    // '@babel/plugin-proposal-numeric-separator',
    // '@babel/plugin-proposal-optional-chaining',
    // '@babel/plugin-proposal-pipeline-operator',
    // '@babel/plugin-proposal-throw-expressions',
    '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-transform-react-jsx-source',
    // '@babel/plugin-transform-runtime',
  ],
  env: {
    test: {
      presets: ['@babel/preset-env', '@babel/preset-react'],
      plugins: [
        'dynamic-import-node',
        'styled-components',
        '@babel/plugin-proposal-class-properties',
        // '@babel/plugin-proposal-decorators',
        // '@babel/plugin-proposal-do-expressions',
        // '@babel/plugin-proposal-export-default-from',
        // '@babel/plugin-proposal-export-namespace-from',
        // '@babel/plugin-proposal-function-sent',
        // '@babel/plugin-proposal-json-strings',
        // '@babel/plugin-proposal-logical-assignment-operators',
        // '@babel/plugin-proposal-nullish-coalescing-operator',
        // '@babel/plugin-proposal-numeric-separator',
        // '@babel/plugin-proposal-optional-chaining',
        // '@babel/plugin-proposal-pipeline-operator',
        // '@babel/plugin-proposal-throw-expressions',
        '@babel/plugin-syntax-dynamic-import',
        '@babel/plugin-transform-react-jsx-source',
      ],
    },
  },
};

module.exports = config;
