service: sls-finance-client

provider:
  name: aws
  profile: serverless-admin
  region: us-east-1
  stage: dev

plugins:
  - serverless-s3bucket-sync

custom:
  s3-sync:
    - folder: app/bin
      bucket: example
